config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  root to: "homes#top"
  get "home/about", to: "homes#about"
  resources :books
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end

  #ゲストログイン機能追加-------------------------------------
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end
  #------------------------------------------------------------

  validates :name,
    presence: true,
    length: { minimum: 2, maximum: 20,
              too_short: "Name is too short (minimum is 2 characters)",
              too_long: "Name is too long (maximum is 20 characters)" },
    uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about] # top,aboutの2つのアクションのみ、ログインなしでもアクセスを可能にする
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user) # ログイン直後は、ユーザーの詳細ページへ遷移
  end
  
  def after_sign_out_path_for(resource) #ログアウト直後は、topへ遷移
    root_path
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id]) #bookの取得
    if @book.update(book_params) #bookのアップデート
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id) #bookの詳細ページへのパス
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id]) #bookの取得
    @book.destroy # データ（レコード）を削除
    redirect_to '/books'
  end

  private

  def book_params #ストロングパラメータ
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    user = book.user
    unless user.id == current_user.id
      redirect_to books_path
    end 
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]
  
  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id]) #ユーザーの取得
    if @user.update(user_params) #ユーザーのアップデート
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id) #ユーザーの詳細ページへのパス
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end 
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class = "container">
  <div class = "row">
    <div class ="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
      <div class = "error_explanation">
        <% if @book.errors.any? %>
          <strong><%= @book.errors.count %> error prohibited this obj from being saved:</strong>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <%= form_with model: @book do |f| %>
        <label for="inputTitle">Title</label><br>
        <%= f.text_field :title, autofocus: true, id:"inputTitle" %><br>
        <label for="inputBody">Opinion</label><br>
        <%= f.text_area :body, autofocus: true, id:"inputBody" %><br>
        <%= f.submit "Update Book" %>
      <% end %>
      <%= link_to 'Show', book_path(@book) %>
      <%= link_to 'Back', '/books' %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class = "error_explanation">
    <% if @book.errors.any? %>
      <strong><%= @book.errors.count %> error prohibited this obj from being saved:</strong>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class='row'>
    <%= render 'users/sidebar', user: @user, book: @book %>
    <div class = 'col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class = "table table-hover table-inverse">
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </thead> <!-- 全ユーザーのbookの一覧表示 -->
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image(50,50) %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p><%= flash[:notice] %></p>
<div class='container px-5 px-sm-0'>
  <div class = "error_explanation">
    <% if @book.errors.any? %>
      <strong><%= @book.errors.count %> error prohibited this obj from being saved:</strong>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class='row'>
    <%= render 'users/sidebar', user: @user, book: @book_new %>
    <div class = 'col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class = "table table-hover table-inverse">
        <tr>
          <td>
            <%= link_to user_path(@user.id) do %>
              <%= image_tag @user.get_profile_image(100,100) %><br>
              <%= @user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@book.id) do %>
              <%= @book.title %>
            <% end %>
          </td>
          <td><%= @book.body %></td>

          <td>
            <% if @book.user == current_user %>
              <%= link_to "Edit", edit_book_path(@book) %>
            <% end %>
          </td>
          <td>
            <% if @book.user == current_user %>
              <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class = 'container'>
  <div class = 'row'>
    <h1 class ="px-3 mx-auto">Welcome to
      <i class = "fas fa-book"></i>
      <strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<p><%= flash[:notice] %></p>
<div class = "container">
  <div class = "row">
    <div class = "mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class ="fa-solid fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>in <i class = "fa-solid fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and enotions</p>
      <p>about various books!</p>
      
      <div class = "btn-wrapper col-10 mx-auto">
        
        <div class="row">
          <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
        </div>
        
        <div class = "row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
        </div>
        
        <div class = "row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
        </div>
        
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class = 'container mt-5'>
    <div class = 'row'>
      <div class = 'mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
    <div class = "container">
      <a class = "navbar-brand" href ="/"><span>Bookers</span></a>
      <button class = "navbar-toggler" type = "button" data-toggler = "collapse" data-target = "#navbarNavDropdown" aria-controls = "navbarNavDropdown" aria-expanded = "false" aria-label = "Toggle navigation">
        <span class = "navbar-toggler-icon"></span>
      </button>
      <div class = "collapse navbar-collapse" id = "navbarNavDropdown">
        <ul class = "navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li><!-- ログイン後のHomeリンク-->
              <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
                <i class = "fa-solid fa-house"></i>Home
              <% end %>
            </li>
            <li><!-- ログイン後のUsersリンク-->
              <%= link_to users_path, class: "nav-link text-light" do %>
                <i class="fa-solid fa-users"></i>Users
              <% end %>
            </li>
            <li><!-- ログイン後のBooksリンク-->
              <%= link_to books_path, class: "nav-link text-light" do %>
                <i class="fa-solid fa-book-open"></i>Books
              <% end %>
            </li>
            <li><!-- ログイン後のLog outリンク-->
              <%= link_to  destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
                <i class="fa-solid fa-right-from-bracket"></i>
                Log out
              <% end %>
            </li>
          <% else %>
            <li><!-- ログイン前のHomeリンク-->
              <%= link_to root_path, class: "nav-link text-light" do %>
                <i class = "fa-solid fa-house"></i>Home
              <% end %>
            </li>
            <li><!-- ログイン前のAboutリンク-->
              <%= link_to home_about_path, class: "nav-link text-light" do %>
                <i class = "fa-solid fa-link"></i>About
              <% end %>
            </li>
            <li><!-- ログイン前のSign upリンク-->
              <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                <i class = "fa-solid fa-user-plus"></i>
                Sign up
              <% end %>
            </li>
            <li><!-- ログイン前のLog inリンク-->
              <%= link_to new_user_session_path, class:"nav-link text-light" do %>
                <i class = "fa-solid fa-right-to-bracket"></i>
                Log in
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/2a91f0927f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_sidebar.html.erb
<div class='col-md-3'>
  <h2>User info</h2>
  
  <table class='table'>
    <tr>
      <%= image_tag user.get_profile_image(100,100) %>
    </tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </table>
  
  <% unless user.guest_user? %><!--ゲストログイン時は編集ボタンを表示しない(ゲストでない時は編集ボタンを表示する)-->
    <div class="row">
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </div>
  <% end %>
  
  <h2 class="mt-3">New book</h2>
  <%= form_with model: book, url: '/books', method: :post do |f| %>
    <label for ="book_title">Title</label><br>
    <%= f.text_field :title %><br>
    <label for ="book_title">Opinion</label><br>
    <%= f.text_area :body %><br>
    <%= f.submit 'Create Book',class: "btn btn-success" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class = "container">
  <div class = "row">
    <div class ="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <div class = "error_explanation">
        <% if @user.errors.any? %>
          <strong><%= @user.errors.count %>error prohibited this obj from being saved:</strong>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <%= form_with model: @user do |f| %>
        <label for="inputName">Name</label><br>
        <%= f.text_field :name, autofocus: true, id:"inputName" %><br>
        <label for="inputImage">Image</label><br>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %><br>
        <label for="inputName">Introduction</label><br>
        <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction" %><br>
        <%= f.submit "Update User" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class = "error_explanation">
    <% if @book.errors.any? %>
      <strong><%= @book.errors.count %> error prohibited this obj from being saved:</strong>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class='row'>
    <%= render 'users/sidebar', user: @user, book: @book %>
    <div class = 'col-md-8 offset-md-1'>
      <h2>Users</h2>
      <table class = "table table-hover table-inverse">
        <thead>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </thead>
        <% @users.each do |user| %>
          <thead>
            <th><%= image_tag user.get_profile_image(50,50) %></th>
            <th><%= user.name %></th>
            <th><%= link_to "Show", user_path(user) %></th>
          </thead>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p><%= flash[:notice] %></p>
<div class='container px-5 px-sm-0'>
  <div class = "error_explanation">
    <% if @book.errors.any? %>
      <strong><%= @book.errors.count %> error prohibited this obj from being saved:</strong>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class='row'>
    <%= render 'users/sidebar', user: @user, book: @book %>
    <div class = 'col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class = "table table-hover table-inverse">
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </thead> <!-- ユーザー投稿bookの一覧表示 -->
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image(50,50) %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>